# Generated by Django 4.2.7 on 2023-12-05 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('departamento', models.CharField(choices=[('otro', 'Otro'), ('contabilidad', 'Contabilidad'), ('rrhh', 'RRHH'), ('legal', 'Legal'), ('informatica', 'Informatica')], default='Otro', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_asignados', to='app1.usuarios')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_creados', to='app1.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Prioridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridad', models.CharField(choices=[('Normal', 'normal'), ('Baja', 'baja'), ('Alta', 'alta')], default='Normal', max_length=20)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('FK_id_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prioridades', to='app1.ticket')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prioridades_creadas', to='app1.usuarios')),
                ('usuario_modificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prioridades_modificadas', to='app1.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Abierto', 'abierto'), ('En progreso', 'en_progreso'), ('Cerrado', 'cerrado')], default='Abierto', max_length=20)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('FK_id_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='app1.ticket')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados_creados', to='app1.usuarios')),
                ('usuario_modificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados_modificados', to='app1.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField()),
                ('FK_id_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='app1.ticket')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.usuarios')),
            ],
        ),
    ]
