# Generated by Django 4.2.7 on 2023-12-12 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='asignado_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prioridad',
            name='FK_id_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prioridades', to='app1.ticket'),
        ),
        migrations.AddField(
            model_name='prioridad',
            name='usuario_creacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prioridades_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prioridad',
            name='usuario_modificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prioridades_modificadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estado',
            name='FK_id_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='app1.ticket'),
        ),
        migrations.AddField(
            model_name='estado',
            name='usuario_creacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estado',
            name='usuario_modificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comentario',
            name='FK_id_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='app1.ticket'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
